### ISSUE TITLE
Elements Icon-Shortcode: Umstellung auf Font Awesome 6

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/WP-Dokumentation#11]
Umstellung auf Font Awesome 6

**Comment by cassandre** [comment]
Suche: https://fontawesome.com/search?m=free

Neu: icon="regular bookmark"
Die meisten Icons sind solid, daher ist solid Standard und kann weggelassen werden. Nur wenn man icons aus dem regular oder brands-Subset braucht, muss man es durch ein Leerzeichen getrennt angeben. D.h. icon="bookmark" funktioniert auch.

Die Parameter `style` und `color` bleiben wie gehabt.
