### ISSUE TITLE
RRZE-Elements: Shortcode text-columns neu

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/WP-Dokumentation#17]
Shortcode: 
- `[text-columns]...[/text-columns]`

Attribute:
- `number`: maximale Anzahl an Spalten (abhängig von Bildschirmbreite), Standard: 2
- `width`: Mindestbreite der Spalten (abhängig von Bildschirmbreite), Standard: 200
- `rule`: Trennlinie anzeigen, Standard: treu
- `rule-color`: Farbe der Trennlinie, Standard: var(--color-ContentBorders, #C3C3CB)
- `background-color`: Hintergrundfarbe, Standard: keine
- `border-color`: Farbe der Umrandung, Standard: keine
- `font`: Schriftfarbe, wahlweise `dark` oder `light`, Standard: dark
- `style`: Vordefinierter Stil, wahlweise `success`, `info`, `warning`, `danger`, `example`
Die letzten vier Attribute funktionieren analog zu den Alerts.

**Comment by lukasniebler** [comment]
@cassandre - Mir ist aufgefallen, dass das Attribut font="light" bei mir nicht funktioniert.
https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/mehrspaltige-texte/

(Außer ich hab da einen Denkfehler drin?) - Anfangs hatte ich einen Schwarzen Hintergrund gesetzt und font="light", aber die Font blieb bei mir ein dunkles Grau.

**Comment by cassandre** [comment]
Sieht für mich jetzt gut aus. Hing sicher auch mit dem Cache-Problem zusammen.
