### ISSUE TITLE
RRZE-Elements: Shortcode tabs neu

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/WP-Dokumentation#19]
Shortcode:
```
[tabs]
[tab title="Titel 1"]...[/tab]
[tab title="Titel 2"]...[/tab]
[tab title="Titel 3"]...[/tab]
[/tabs]
```

Attribute [tabs]:
- `color`: Mögliche Werte: fau, phil, nat, med, rw, tf; Standard: die Farbe des eigenen Themes

Attribute [tab]:
- `title`: **Muss** angegeben werden. Steht oben in den Tabs.
- `icon`: Fontawesome 6, siehe Accordion
- `suffix`: Steht in bold hinter dem Titel, siehe Accordion

**Comment by lukasniebler** [comment]
@cassandre - Gibt es für die Tab-Gruppen auch hstart?
Ich habe die jetzt mal hier ausprobiert:
https://www.wordpress.rrze.fau.de/plugins/inhaltsseiten-mit-funktionen-erweitern/elements/mehrspaltige-texte/
Funktionieren auch Prima. Aber die Überschrift ist bei mir dann eine h1, wenn ich das richtig gesehen habe?
